/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_var_1;

public class App {
    
//import java.util.Scanner;
        

    
    /*public static void main(String[] args) {
        String lineadeteclado;
        
        Scanner miScan = new Scanner(System.in);
        
        lineadeteclado = miScan.nextLine();
        
        System.out.println("Esto sale en el terminal " + lineadeteclado);
        
        lineadeteclado = miScan.nextLine();
        
        System.out.println("Esto sale en el terminal " + lineadeteclado);
    }*/
    public static void main(String[] args){
        int x = 200;
        int y = 111;
        System.out.println("x = "+ x );
        System.out.println("y = "+ y );
        
        int suma = x + y; 
        System.out.println("La suma de las variables es: " + suma);
        
        int resta = x - y; 
        System.out.println("La resta de las variables es: " + resta);
        
        int multi = x * y; 
        System.out.println("La multiplicación de las variables es: " + multi);
        
        float div = (float)x / y; 
        System.out.println("La división de las variables es: " + div);
    }
}
    
